version: '3.2'
services:
  web:
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './logs:/logs'
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - './database/data:/var/lib/postgresql/data'
